--- 
wpsgeog: 
  image: bigwxwrf/ncar-wpsgeog
wrfinput: 
  image: bigwxwrf/ncar-wrfinputsandy
wrfsandy-leader: 
  command: 
    - /wrf/run-wrf
    - "-np"
    - "192"
    - "-slots"
    - "64"
    - "-iface"
    - eth0
    - "-hosts"
    - "wrfleader,wrfslave-1,wrfslave-2"
  container_name: wrfleader
  links: 
    - wrfsandy-slave-1
    - wrfsandy-slave-2
  image: bigwxwrf/ncar-wrf
  volumes: 
    - "~/wrfoutput:/wrfoutput"
  volumes_from: 
    - wpsgeog
    - wrfinput
wrfsandy-slave-1: 
  command: 
    - /wrf/slave
  container_name: wrfslave-1
  image: bigwxwrf/ncar-wrf
wrfsandy-slave-2: 
  command: 
    - /wrf/slave
  container_name: wrfslave-2
  image: bigwxwrf/ncar-wrf
